### ISSUE TITLE
Does not conform to the syntax reference

### ISSUE THREAD

**Issue by StratusFearMe21** [treeman/tree-sitter-djot#38]
At the beginning of the syntax reference, there are a number of examples of how precedence works in `djot`. <https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#precedence>. This is how the parser parses these examples currently

Here are some examples that don't parse correctly.

![20240509_17h28m23s_grim](https://github.com/treeman/tree-sitter-djot/assets/57533634/96b58225-c847-46cd-9d65-b811d44056ab)
![20240509_17h28m28s_grim](https://github.com/treeman/tree-sitter-djot/assets/57533634/7671bf26-6ce7-457a-9534-dc479c22a2e6)

(no smart punctuation)
![20240509_17h35m14s_grim](https://github.com/treeman/tree-sitter-djot/assets/57533634/f77b3df2-f964-4a85-a04d-8ea77f97adce)

(First quotation mark parsed, but not the second)
![20240509_17h37m42s_grim](https://github.com/treeman/tree-sitter-djot/assets/57533634/7f34b3cc-57ce-4c59-ae23-c6b0b6831103)

(Quotation marks are not escaped)
![20240509_17h38m52s_grim](https://github.com/treeman/tree-sitter-djot/assets/57533634/03253296-d073-43b0-9d08-4abc4bc2a46e)

Causes errors to be produced in the syntax tree

```markdown
> This is a block quote.
>
> 1. with a
> 2. list in it.
```

**Comment by StratusFearMe21** [comment]
That's all the examples I could find. All this being said though, this is some incredible work that you've done here! Having an incremental parser available for this relatively obscure language has been so useful to me, and I'd like to thank you so much for making this! :smile:

**Comment by treeman** [comment]
Excellent, thank you. I'll take a look when I have time left over.

**Comment by StratusFearMe21** [comment]
Found a few things:

1. The examples for quotation marks have a very easy fix

```diff
diff --git a/grammar.js b/grammar.js
index b16ef99..0465167 100644
--- a/grammar.js
+++ b/grammar.js
@@ -573,7 +573,7 @@ module.exports = grammar({
 
     _smart_punctuation: ($) =>
       choice($.quotation_marks, $.ellipsis, $.em_dash, $.en_dash),
-    quotation_marks: (_) => token(choice('{"', '"}', "{'", "'}", '\\"', "\\'")),
+    quotation_marks: (_) => token(choice('{"', '"}', "{'", "'}", '"', "'")),
     ellipsis: (_) => "...",
     em_dash: (_) => "---",
     en_dash: (_) => "--",
```

2. The block quote example *does not* produce errors in the syntax tree, it's just when there's not a final newline at the end of the document that it doesn't like that. I also found this to be true with footnotes.

**Comment by treeman** [comment]
I've broken out problems into standalone issues, see: #49, #50, #51, #52.

As for the quotation marks I don't think it's that simple as we don't want to mark `'` in `it's` for example, and we also need to have matching pairs I guess? It's more annoying to implement and I don't currently have a plan for how to do it correctly.

The emphasis/strong issues are... Hard I think. If we need to match the minimal substring then we may not be able to rely on the tree-sitter grammar specification as I'd hoped and we may need to handle it in the scanner, but I don't see how I'd implement that in a way that works with everything else...

That quotation marks aren't escaped in `5\'11\'` and are parsed as `quotation_marks` is a conscious decision I made as Djot treats them as "straight quotes". I don't differ between the different types of quotes though, I don't know what's the best approach.

The list in blockquote errors is fixed in https://github.com/treeman/tree-sitter-djot/pull/48, although the second marker isn't properly identified (tracked in #47).
